default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: project_conversation_history_development

test:
  <<: *default
  database: project_conversation_history_test

production:
  primary: &primary_production
    <<: *default
    database: project_conversation_history_production
    username: project_conversation_history
    password: <%= ENV["PROJECT_CONVERSATION_HISTORY_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: project_conversation_history_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: project_conversation_history_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: project_conversation_history_production_cable
    migrations_paths: db/cable_migrate
